@c Information For Everyone chapter...
@node Information For Everyone
@chapter Information For Everyone

@include "Information For Everyone/Orientation.texi"
@include "Information For Everyone/Code of Conduct.texi"
@include "Information For Everyone/Specialties.texi"
@include "Information For Everyone/Socioeconomic Modelling.texi"
@c @include "Information For Everyone/Current Members.texi"
@include "Information For Everyone/Communication.texi"
@include "Information For Everyone/Introduction to Launchpad.texi"
@include "Information For Everyone/Revision Control Management.texi"
@include "Information For Everyone/Rationale for Bazaar Revision Control.texi"
@include "Information For Everyone/Blueprints.texi"

@c @section Fonts
@c @section Colour Scheme
@c @section Theme


