\input texinfo.tex
@c Above tells TEX to use the ‘texinfo.tex’ file, which tells TEX how 
@c to translate the Texinfo commands into TEX typesetting commands...

@c Set file name for output and tell TEX to open auxiliary files.
@c  everything before this line is ignored...
@setfilename "Handbook"
@documentencoding UTF-8

@c Set title for page headers / footers...
@include Version.texi
@settitle Avaneya Crew Handbook @value{VERSION_MANUAL}

@c Macros...
@set MANUAL_TITLE           Avaneya Crew Handbook
@set MANUAL_DESCRIPTION     A comprehensive guide for all of our bold contributors.
@set AVANEYA_DESCRIPTION    A cerebral science fiction game for GNU.
@set COPYRIGHT_LINE         @copyright{} 2010, 2011 Kshatra Corp

@c Copyright notice...
@copying
@value{MANUAL_DESCRIPTION}

@sp 1
Copyright @value{COPYRIGHT_LINE}.
@sp 1

@quotation
Permission is granted to copy, distribute and/or modify this document 
under the terms of the GNU Free Documentation License, Version 1.3 or 
any later version published by the Free Software Foundation; with no 
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. A 
copy of the license is included in @ref{License GFDL}.
@end quotation
@end copying

@c Start title page...
@titlepage
@title @value{MANUAL_TITLE}
@subtitle @value{MANUAL_DESCRIPTION}
@author The Avaneya Crew
last updated @value{VERSION_MANUAL}.

@c Document description...
@documentdescription
@value{MANUAL_DESCRIPTION}
@end documentdescription

@c Copyright page...
@page
@vskip 0pt plus 1filll
@insertcopying
@sp 1

@c End the title page and begin page numbering...
@end titlepage 

@c Output the table of contents at the beginning...
@summarycontents
@contents

@c Top / master node...
@ifnottex
@node Top
@top @value{MANUAL_TITLE}
@value{MANUAL_DESCRIPTION}
@end ifnottex

@c Main body follows...
@include "Preface/Preface.texi"
@include "The Game/The Game.texi"
@include "Understanding Avaneya/Understanding Avaneya.texi"
@include "Timeline/Timeline.texi"
@include "The Characters/The Characters.texi"
@include "The Story/The Story.texi"
@include "The Game World/The Game World.texi"
@include "Gameplay/Gameplay.texi"
@c @include "Features/Features.texi"
@include "Selected Technologies/Selected Technologies.texi"
@include "Information For Everyone/Information For Everyone.texi"
@include "Information For Artists/Information For Artists.texi"
@c @include "Information For Audio Engineers/Information For Audio Engineers.texi"
@c @include "Information For Cinematic Artists/Information For Cinematic Artists.texi"
@include "Information For Engineers/Information For Engineers.texi"
@c @include "Information For Modeller/Information For Modeller.texi"
@c @include "Information For Musicians/Information For Musicians.texi"
@c @include "Information For Researchers/Information For Researchers.texi"
@c @include "Information For Scripters/Information For Scripters.texi"
@c @include "Information For System Administrators/Information For System Administrators.texi"
@c @include "Information For Translators/Information For Translators.texi"
@c @include "Information For Voice Actors/Information For Voice Actors.texi"
@c @include "Information For Web Developers/Information For Web Developers.texi"
@c @include "Information For Writers/Information For Writers.texi"
@include "The Project Crew/The Project Crew.texi"
@include "Licensing Rationale/Licensing Rationale.texi"

@c Appendices...
@include "Glossary/Glossary.texi"
@include "Licenses/Licenses.texi"

@c Index...
@node Index
@unnumbered Index
@printindex cp

@c End of document...
@bye

