@c The Game chapter...
@node The Game
@chapter The Game

@section Why?
Too often, people have come out of experiencing a great dystopian science fiction novel or film, only to say to themselves, Thank goodness we don't live in @i{that} world! That needs to change.

Dystopian science fiction can arguably be among the most honest kind of story telling when examined in the context of history. But unless people can see the connection between the world they perceived in fiction and the one they inhabit, vague analogies and cryptic metaphors tend to have minimal utility as pedagogical aids.

But @i{good} science fiction is only @i{partly} fiction because it is often the @i{science} portion that is what attracts people to it in the first place. Science, by its nature, is a thinking and knowledge oriented enterprise - not unlike the people that tend to gravitate towards the aforementioned genre. This can set the bar high for what they expect and requires designers to pay a great deal of attention to detail. A certain degree of artistic license is to be expected, but users still expect it to be as consistent with what we already know to be true or what is at least reasonably plausible. It may be because of the thinking and learning aspect that we are seeing less and less science fiction entertainment as time goes on. That needs to change.

Another important reason is that there is very little, if any, free commercial entertainment for the GNU operating system. When people use GNU, they are treated as second class citizens in terms of the availability of high quality games. Not only are there very few higher production titles that are available for GNU, they are usually proprietary, and even then, generally bad ports using deprecated APIs, poorly packaged, @footnote{That is, if they even bother to use the platform's native distribution's package manager in the first place.} and integrate horribly into the user's desktop - ignoring the usual human factors community driven conventions.

But in terms of their subject matter itself, they tend to appeal more to the senses of the mainstream proprietary user, and thus do not reflect the spirit of a social conscience commonplace in the @i{software libre} community. That also needs to change.

@node Classification
@section Classification
People have struggled in the past to classify Avaneya. It is what it is, but the closest traditional categories that form a subset of it are the traditional city builder and management simulations and the real time strategy.

@node Who Is It For?
@section Who Is It For?
The game so far has attracted a fairly large base of followers. From what can be observed at this time, the game appears to appeal to those with an interest in:

@itemize @bullet
@item
@emph{software libre}
@item 
@emph{a social conscience}
@item
@emph{science fiction}
@item
@emph{the interconnectedness of everything}
@end itemize

The game may take place in the future, but it deals with current problems. The best way to get an idea of the intended audience is to quickly @pxref{Relevant Readings} and to ask yourself the type of audience that those resources would probably appeal to. 

@section Who Is It Not For?
This game will challenge you to think, and maybe even offend you. It is not like other games, and thus it is not for all people. Those who have an attention span of only a few seconds or believe that things originate in cans will simply not enjoy this game. There are already many such games that appeal to that type of audience, so that need not be our aim here.

There is nothing to stop us from taking a guess via something like a rough inversion of the aforementioned. Someone who would not want to play this game might have any of these characteristics:

@itemize @bullet
@item
@emph{indifference or unawareness of the need to protect their freedom, including software freedom}
@item 
@emph{indifference or unawareness to a sense of community}
@item
@emph{no particular preference for the science fiction genre}
@item
@emph{tends to see things disparately rather than as interconnected}
@end itemize


