@c Things to Know If You Are chapter...

@node Artists / Non-Developers

    @node General
    @section General
        @subsection Fonts
        @subsection Colour Scheme
        @subsection Theme

    @node 2D Artist
    @section 2D Artist

    @node Audio Engineer
    @section Audio Engineer

    @node Cinematic Artist
    @section Cinematic Artist

@node Engineer
@section Engineer
@subsection Coding Standards
@subsection Ares Engine Architectural Design

@node Modeller
@section Modeller

@node Musician
@section Musician

@node Researcher
@section Researcher

@node Scripter
@section Scripter

@node System Administrator
@section System Administrator

@node Translator
@section Translator

@node Voice Actor
@section Voice Actor

@node Web Developer
@section Web Developer

@node Writer
@section Writer

