@c License appendix...
@node Licenses
@appendix Licenses

@c GPL v3...
@node License GPL
@appendixsec GNU General Public License
@include "Licenses/GNU General Public License.texi"

@c GFDL 1.3...
@page
@node License GFDL
@appendixsec GNU Free Documentation License
@include "Licenses/GNU Free Documentation License.texi"

@c CC-BY-NC-SA 3.0 Unported...
@page
@node License CC-BY-NC-SA
@appendixsec Creative Commons Attribution-NonCommercial-ShareAlike
@include "Licenses/CC-BY-NC-SA.texi"


