@c Glossary appendix..
@node Glossary
@appendix Glossary

The following is a collection of terms used in the game world that range from the everyday colloquial to technical terminology. Familiarizing yourself with them will be useful in ensuring the game remains as rich as possible.
@sp 1

@c Endothermic reaction...
@noindent
@dfn{@strong{Endothermic reaction}}: A chemical reaction that requires energy to be put into it in order to react. An example would be cooking an egg. The egg doesn't change unless you apply heat to it. This is contrasted with an @emph{exothermic reaction}.
@sp 1

@c Exothermic reaction...
@noindent
@dfn{@strong{Exothermic reaction}}: A chemical reaction that releases energy as part of its reaction. An example would be burning wood. As the wood changes, it releases energy in the form of mostly heat.
@sp 1

@c Genuine Progress Indicator...
@noindent
@dfn{@strong{Genuine Progress Indicator}}: The GPI is a system of true cost accounting which is intended to be a replacement to the GDP, gross domestic product, sometimes called the gross national product, GNP. The GPI works by taking into account all costs of an activity to society and provides a net balance sheet. The latter, on the other hand, only functions as an income sheet by tabulating the total amount of goods and services produced in a year. 

An example where the difference between the two is well illustrated is with the tobacco industry. The GDP would account for the value of all cigarettes sold (a positive figure). Conversely, the GPI would also account for the total value of all units sold, but then go on to subtract the deficits socialized to everyone in the form of health costs, fires, garbage collection, environmental toxicity, and the deaths of approximately 5,000,000@footnote{@emph{Merchants of Doubt: How a Handful of Scientists Obscured the Truth on Issues from Tobacco Smoke to Global Warming}, Naomi Oreskes, Bloomsbury Press, 2010} people every year (a negative figure).
@sp 1

@c Regolith...
@noindent
@dfn{@strong{Regolith}}: What most refer to as dirt. More technically, it is the the loose heterogeneous mixture of material that blankets the solid rock.
@sp 1

@c Rhodium
@node Glossary Rhodium
@noindent
@dfn{@strong{Rhodium}}: An elemental chemical with the symbol Rh and atomic number 45. It is a member of the platinum family and considered to be the most precious metal of that family, even exceeding the value of gold. It is also one of rarist. 

Usually the only way of getting any kind of high quantity mineral is through high-grade ore. This only happens when complex hydrological and volcanic processes have happened, which in our solar system, has only occured on Mars and Earth - hence why the Moon is barren. But unlike the Earth, Martian deposits have remained untapped.
@sp 1

@c RWGS reactor...
@noindent
@dfn{@strong{RWGS reactor}}: The reverse-water-gas-shift reactor is a method of producing oxygen (@math{O_2}) from carbon dioxide (@math{CO_2}). This is useful because the latter is plentiful in the Martian atmosphere at 95 %.

@sp 1
@math{CO_2(g) + H_2(g) \rightarrow O_2(g) + CO(g)}
@sp 1

The process has been known since the mid 1800s and works by reacting carbon dioxide and hydrogen gasses together over a copper-on-alumina catalyst. Aqua (liquid water) and carbon monoxide gas are produced as byproducts. The aqua is split via electrolysis to produce hydrogen and oxygen gasses. The hydrogen can then be recycled back into the reactor and the carbon monoxide purged out into the atmosphere.

The reactor needs to be at @math{400\,^{\circ}{\rm C}} and at low pressure. It requires about 180 watts of power, or about 3 @math{m^2} of solar panels on a fully sunny day's average solar flux. At that energy rate, you can expect to produce about 1 kg per day of oxygen, which is sufficient for a single person. The reactor requires power because it is an @emph{endothermic reaction}. However, it is possible to use a @emph{Sebatier reactor} in tandem, which is an exothermic process, to provide the heat required to drive the RWGS reaction.

To start the process, only a small amount of water is required which acts as a reagent. By importing hydrogen from Earth, it acts to the colonists' advantage in allowing it to be leveraged in the creation of water, or hydrogen gas if needed.
@sp 1

@c Sebatier reactor...
@noindent
@dfn{@strong{Sebatier reactor}}: A chemical process for creating methane @math{CH_4} from @math{CO_2} and hydrogen. This is useful because carbon dioxide gas is plentiful in the Martian atmosphere at 95 %.

@sp 1
@math{CO_2(g) + 4H_2(g) \rightarrow CH_4(g) + 2H_2O(g) + heat}
@sp 1

The reactor needs to be at @math{400\,^{\circ}{\rm C}} and at low pressure. This makes it almost the same as the @emph{RWGS reactor} except that it uses a different catalyst to make methane instead of carbon monoxide. You can either use nickel, which is cheap, or ruthenium-on-alumina, which is safer, but more expensive.
@sp 1

@c Sol...
@noindent
@dfn{@strong{Sol}}: Short for solar day, the length of time a planet takes to rotate completely on its polar axis with respect to the sun. Terrans call this a day, Martians a sol. See also @i{yestersol}.
@sp 1

@c Yestersol...
@noindent
@node Glossary Yestersol
@dfn{@strong{Yestersol}}: The sol preceding the current one. This is the Mars analogue to the Terran yesterday, but different since the length of a sol on both worlds is different.
@sp 1

