@c Understanding Avaneya chapter...
@node Understanding Avaneya
@chapter Understanding Avaneya

A great way to better your understanding of this project is to take a look at what it tries to teach and some of the relevant learning resources behind it. 

The learning resources you should be able to find available either in digital format on the internet, or in physical format at most major book stores. Most of them are not difficult to find.

@include "Understanding Avaneya/Core Leitmotifs.texi"
@include "Understanding Avaneya/Resources For Everyone.texi"
@include "Understanding Avaneya/Resources For Artists.texi"
@include "Understanding Avaneya/Resources For Engineers.texi"


